<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    
    <Version>2.1.0</Version>
    <FileVersion>2.1.0.0</FileVersion>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <Authors>Tolgahan Acar</Authors>
    <Company>MiniMarket System</Company>
  </PropertyGroup>
</Project>